-- 每日浏览量记录表
-- 用于记录每天所有模型的总浏览量，支持按日期查询历史数据
CREATE TABLE IF NOT EXISTS daily_model_views (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  view_date DATE NOT NULL COMMENT '浏览日期',
  total_views INT NOT NULL DEFAULT 0 COMMENT '当日总浏览量',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  UNIQUE KEY uk_view_date (view_date) COMMENT '日期唯一约束',
  INDEX idx_view_date (view_date) COMMENT '日期索引'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='每日模型浏览量记录表';

-- 插入最近14天的记录（如果不存在）
INSERT IGNORE INTO daily_model_views (view_date, total_views)
SELECT 
  DATE(DATE_SUB(CURDATE(), INTERVAL n DAY)) as view_date,
  0 as total_views
FROM (
  SELECT 0 as n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION 
  SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION 
  SELECT 10 UNION SELECT 11 UNION SELECT 12 UNION SELECT 13
) numbers
WHERE DATE(DATE_SUB(CURDATE(), INTERVAL n DAY)) >= DATE_SUB(CURDATE(), INTERVAL 13 DAY);
